require("settings.options")
require("settings.keymaps")
require("settings.plugins")

require("plugins.colors")
require("plugins.lualine")
require("plugins.nvimtree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.autoclose")
require("plugins.dressing")
